#!/usr/bin/env python3
import argparse
import json
import os
import subprocess
from pathlib import Path


def _has_ctl(s: str) -> bool:
    return any((ord(ch) < 32) or (ord(ch) == 127) for ch in (s or ""))


def _safe_cf_value(s: str) -> str:
    """Prevent config injection: no newlines/control chars in values."""
    s = str(s or "").strip()
    if not s or _has_ctl(s) or "\n" in s or "\r" in s or "\x00" in s:
        raise ValueError("invalid config value")
    return s

MAIN_CF_TEMPLATE = r"""
# Generated by ms365-relay
compatibility_level = 3.6

myhostname = {hostname}
mydomain = {domain}
myorigin = $mydomain

inet_interfaces = all
inet_protocols = ipv4

# Accept mail for relay only
mydestination =
local_recipient_maps =

# Relay out via Microsoft 365
relayhost = {relayhost}

# Trusted subnets allowed to relay without AUTH
mynetworks = {mynetworks}

# Basic restrictions
smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, defer_unauth_destination

# TLS inbound (smtpd)
smtpd_tls_cert_file = {tls_cert}
smtpd_tls_key_file = {tls_key}
smtpd_tls_loglevel = 1
smtpd_tls_received_header = yes

# TLS outbound (smtp)
smtp_tls_security_level = encrypt
smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
smtp_tls_session_cache_database = lmdb:${{data_directory}}/smtp_scache
smtp_tls_loglevel = 1
smtp_always_send_ehlo = yes

# Client AUTH (for incoming)
smtpd_sasl_auth_enable = yes
smtpd_sasl_type = cyrus
smtpd_sasl_security_options = noanonymous
broken_sasl_auth_clients = yes

# Enforce "From" ownership for authenticated users (generated map)
smtpd_sender_login_maps = lmdb:/etc/postfix/sender_login_maps
smtpd_sender_restrictions = reject_sender_login_mismatch

# XOAUTH2 for outbound relay
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = lmdb:/etc/postfix/sasl_passwd
smtp_sasl_security_options =
smtp_sasl_mechanism_filter = xoauth2

# Size limits
message_size_limit = 52428800
""".lstrip()

MASTER_CF = r"""
# Generated by ms365-relay
# Based on the upstream Postfix master.cf defaults, plus our smtp/submission overrides.

# ====================================================================
# service type  private unpriv  chroot  wakeup  maxproc command + args
#               (yes)   (yes)   (yes)   (never) (100)
# ====================================================================

# Postfix 3.8+ uses the postlog service for internal logging.
postlog   unix-dgram n       -       n       -       1       postlogd

smtp      inet  n       -       n       -       -       smtpd
  -o smtpd_tls_security_level={tls_25}

pickup    unix  n       -       n       60      1       pickup
cleanup   unix  n       -       n       -       0       cleanup
qmgr      unix  n       -       n       300     1       qmgr
#qmgr     unix  n       -       n       300     1       oqmgr

tlsmgr    unix  -       -       n       1000?   1       tlsmgr

rewrite   unix  -       -       n       -       -       trivial-rewrite
bounce    unix  -       -       n       -       0       bounce
defer     unix  -       -       n       -       0       bounce
trace     unix  -       -       n       -       0       bounce
verify    unix  -       -       n       -       1       verify
flush     unix  n       -       n       1000?   0       flush
proxymap  unix  -       -       n       -       -       proxymap
proxywrite unix -       -       n       -       1       proxymap

showq     unix  n       -       n       -       -       showq
error     unix  -       -       n       -       -       error
retry     unix  -       -       n       -       -       error
discard   unix  -       -       n       -       -       discard

# Outbound SMTP client transport (required for relayhost delivery)
smtp      unix  -       -       n       -       -       smtp

local     unix  -       n       n       -       -       local
virtual   unix  -       n       n       -       -       virtual
lmtp      unix  -       -       n       -       -       lmtp

anvil     unix  -       -       n       -       1       anvil
scache    unix  -       -       n       -       1       scache

# Submission (587) - AUTH required
submission inet n       -       n       -       -       smtpd
  -o syslog_name=postfix/submission
  -o smtpd_tls_security_level={tls_587}
  -o smtpd_tls_auth_only=yes
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_client_restrictions=permit_sasl_authenticated,reject
  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
  -o milter_macro_daemon_name=ORIGINATING

""".lstrip()


def postmap(path: Path):
    # We configure Postfix to use lmdb: maps; ensure postmap generates the right DB type.
    # (On Debian the default database type is usually hash, which would create .db files.)
    subprocess.check_call(["postmap", f"lmdb:{path}"])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True)
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--token-dir", required=True)
    ap.add_argument("--tls-cert", required=True)
    ap.add_argument("--tls-key", required=True)
    args = ap.parse_args()

    with open(args.config, "r", encoding="utf-8") as f:
        cfg = json.load(f)

    hostname = os.environ.get("RELAY_HOSTNAME", cfg.get("hostname", "relay.local"))
    domain = os.environ.get("RELAY_DOMAIN", cfg.get("domain", "local"))
    mynet_env = os.environ.get("RELAY_MYNETWORKS")
    if mynet_env:
        # allow comma or space separated
        parts = [p.strip() for p in mynet_env.replace(",", " ").split() if p.strip()]
        mynetworks = ", ".join(parts)
    else:
        mynetworks = ", ".join(cfg.get("mynetworks", ["127.0.0.0/8"]))

    relayhost = os.environ.get("RELAYHOST") or cfg.get("relayhost") or "[smtp.office365.com]:587"

    tls_cfg = cfg.get("tls") or {}
    tls_25 = os.environ.get("RELAY_SMTPD_TLS_LEVEL_25") or tls_cfg.get("smtpd_25") or "may"
    tls_587 = os.environ.get("RELAY_SMTPD_TLS_LEVEL_587") or tls_cfg.get("smtpd_587") or "encrypt"

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    main_cf = MAIN_CF_TEMPLATE.format(
        hostname=_safe_cf_value(hostname),
        domain=_safe_cf_value(domain),
        relayhost=_safe_cf_value(relayhost),
        mynetworks=_safe_cf_value(mynetworks),
        tls_cert=_safe_cf_value(args.tls_cert),
        tls_key=_safe_cf_value(args.tls_key),
    )
    (outdir / "main.cf").write_text(main_cf, encoding="utf-8")
    (outdir / "master.cf").write_text(MASTER_CF.format(tls_25=tls_25, tls_587=tls_587), encoding="utf-8")

    # Outbound xoauth2 token file mapping
    ms365_user = os.environ.get("MS365_SMTP_USER", "").strip() or str((cfg or {}).get("ms365_smtp_user") or "").strip()
    sasl_passwd = outdir / "sasl_passwd"
    if ms365_user:
        # token file path must be a safe filename
        import re as _re
        safe = _re.sub(r"[^A-Za-z0-9_.@+\-]", "_", ms365_user.strip())
        while ".." in safe:
            safe = safe.replace("..", "__")
        safe = safe.strip("._-")[:128]
        token_file = str(Path(args.token_dir) / safe)
        sasl_passwd.write_text(f"{relayhost} {ms365_user}:{token_file}\n", encoding="utf-8")
        os.chmod(sasl_passwd, 0o600)
        postmap(sasl_passwd)

    # Sender login map (envelope sender -> sasl login)
    allowed_from = cfg.get("allowed_from", {}) or {}
    lines = []

    def _safe_map_token(s: str) -> str:
        s = str(s or "").strip()
        if not s or _has_ctl(s) or any(ch.isspace() for ch in s) or "/" in s or "\\" in s:
            raise ValueError("invalid map token")
        return s

    # allowed_from can be {"user": ["from1", "from2"]}
    for login, from_list in allowed_from.items():
        login = _safe_map_token(login)
        for addr in from_list or []:
            addr = _safe_map_token(str(addr).strip().lower())
            if addr:
                lines.append(f"{addr} {login}\n")

    sender_login_maps = outdir / "sender_login_maps"
    sender_login_maps.write_text("".join(lines), encoding="utf-8")
    postmap(sender_login_maps)


if __name__ == "__main__":
    main()
