#!/usr/bin/env python3
import argparse
import json
import os
import sqlite3
import subprocess
from pathlib import Path


def _has_ctl(s: str) -> bool:
    return any((ord(ch) < 32) or (ord(ch) == 127) for ch in (s or ""))


def _safe_cf_value(s: str) -> str:
    """Prevent config injection: no newlines/control chars in values."""
    s = str(s or "").strip()
    if not s or _has_ctl(s) or "\n" in s or "\r" in s or "\x00" in s:
        raise ValueError("invalid config value")
    return s

MAIN_CF_TEMPLATE = r"""
# Generated by ms365-relay
compatibility_level = 3.6

myhostname = {hostname}
mydomain = {domain}
myorigin = $mydomain

inet_interfaces = all
inet_protocols = ipv4

# Accept mail for relay only
mydestination =
local_recipient_maps =

# Relay out via Microsoft 365
relayhost = {relayhost}

# Trusted subnets allowed to relay without AUTH
mynetworks = {mynetworks}

# Basic restrictions
smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, defer_unauth_destination

# TLS inbound (smtpd)
smtpd_tls_cert_file = {tls_cert}
smtpd_tls_key_file = {tls_key}
smtpd_tls_loglevel = 1
smtpd_tls_received_header = yes

# TLS outbound (smtp)
smtp_tls_security_level = {smtp_tls_security_level}
smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
smtp_tls_session_cache_database = lmdb:${{data_directory}}/smtp_scache
smtp_tls_loglevel = 1
smtp_always_send_ehlo = yes

# Client AUTH (for incoming)
# Use Dovecot auth socket for predictable SASL behavior across distros.
smtpd_sasl_auth_enable = yes
smtpd_sasl_type = dovecot
smtpd_sasl_path = private/auth
smtpd_sasl_security_options = noanonymous
broken_sasl_auth_clients = yes

# Enforce "From" ownership for authenticated users (generated map)
smtpd_sender_login_maps = lmdb:/etc/postfix/sender_login_maps
smtpd_sender_restrictions = reject_sender_login_mismatch

# Rewrite locally-generated envelope senders (e.g. DSNs) to a valid From for relayhost.
# This avoids Microsoft 365 rejecting MAILER-DAEMON / postmaster send-as.
sender_canonical_maps = lmdb:/etc/postfix/sender_canonical
sender_canonical_classes = envelope_sender

# XOAUTH2 for outbound relay
{outbound_sasl_block}

# Size limits
message_size_limit = 52428800
""".lstrip()

MASTER_CF = r"""
# Generated by ms365-relay
# Based on the upstream Postfix master.cf defaults, plus our smtp/submission overrides.

# ====================================================================
# service type  private unpriv  chroot  wakeup  maxproc command + args
#               (yes)   (yes)   (yes)   (never) (100)
# ====================================================================

# Postfix 3.8+ uses the postlog service for internal logging.
postlog   unix-dgram n       -       n       -       1       postlogd

smtp      inet  n       -       n       -       -       smtpd
  -o smtpd_tls_security_level={tls_25}
  -o smtpd_tls_auth_only=yes

pickup    unix  n       -       n       60      1       pickup
cleanup   unix  n       -       n       -       0       cleanup
qmgr      unix  n       -       n       300     1       qmgr
#qmgr     unix  n       -       n       300     1       oqmgr

tlsmgr    unix  -       -       n       1000?   1       tlsmgr

rewrite   unix  -       -       n       -       -       trivial-rewrite
bounce    unix  -       -       n       -       0       bounce
defer     unix  -       -       n       -       0       bounce
trace     unix  -       -       n       -       0       bounce
verify    unix  -       -       n       -       1       verify
flush     unix  n       -       n       1000?   0       flush
proxymap  unix  -       -       n       -       -       proxymap
proxywrite unix -       -       n       -       1       proxymap

showq     unix  n       -       n       -       -       showq
error     unix  -       -       n       -       -       error
retry     unix  -       -       n       -       -       error
discard   unix  -       -       n       -       -       discard

# Outbound SMTP client transport (required for relayhost delivery)
smtp      unix  -       -       n       -       -       smtp

local     unix  -       n       n       -       -       local
virtual   unix  -       n       n       -       -       virtual
lmtp      unix  -       -       n       -       -       lmtp

anvil     unix  -       -       n       -       1       anvil
scache    unix  -       -       n       -       1       scache

# Submission (587) - AUTH required
submission inet n       -       n       -       -       smtpd
  -o syslog_name=postfix/submission
  -o smtpd_tls_security_level={tls_587}
  -o smtpd_tls_auth_only=yes
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_client_restrictions=permit_sasl_authenticated,reject
  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
  -o milter_macro_daemon_name=ORIGINATING

""".lstrip()


def postmap(path: Path):
    # We configure Postfix to use lmdb: maps; ensure postmap generates the right DB type.
    # (On Debian the default database type is usually hash, which would create .db files.)
    subprocess.check_call(["postmap", f"lmdb:{path}"])


def _safe_map_token(value: object) -> str:
    token = str(value or "").strip()
    if (
        not token
        or _has_ctl(token)
        or any(ch.isspace() for ch in token)
        or "/" in token
        or "\\" in token
    ):
        raise ValueError("invalid map token")
    return token


def render_sender_login_map(allowed_from: object) -> str:
    """Render one LMDB key per sender with all authorized SMTP logins."""
    if not isinstance(allowed_from, dict):
        raise ValueError("allowed_from must be a mapping")

    senders: dict[str, list[str]] = {}
    for raw_login, from_list in allowed_from.items():
        login = _safe_map_token(raw_login)
        if not isinstance(from_list, list):
            raise ValueError("allowed_from address lists must be lists")
        for raw_address in from_list:
            address = _safe_map_token(raw_address).lower()
            authorized_logins = senders.setdefault(address, [])
            if login not in authorized_logins:
                authorized_logins.append(login)

    return "".join(
        f"{address} {','.join(logins)}\n" for address, logins in senders.items()
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True)
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--token-dir", required=True)
    ap.add_argument("--tls-cert", required=True)
    ap.add_argument("--tls-key", required=True)
    args = ap.parse_args()

    if args.config.endswith(".db"):
        with sqlite3.connect(f"file:{args.config}?mode=ro", uri=True) as conn:
            row = conn.execute("SELECT config FROM settings WHERE id = 1").fetchone()
        if not row:
            raise RuntimeError("SQLite settings row is missing")
        cfg = json.loads(row[0])
    else:
        with open(args.config, "r", encoding="utf-8") as f:
            cfg = json.load(f)

    hostname = cfg.get("hostname") or os.environ.get("RELAY_HOSTNAME", "relay.local")
    domain = cfg.get("domain") or os.environ.get("RELAY_DOMAIN", "local")
    mynet_env = os.environ.get("RELAY_MYNETWORKS")
    if cfg.get("mynetworks"):
        mynetworks = ", ".join(cfg["mynetworks"])
    elif mynet_env:
        # allow comma or space separated
        parts = [p.strip() for p in mynet_env.replace(",", " ").split() if p.strip()]
        mynetworks = ", ".join(parts)
    else:
        mynetworks = "127.0.0.0/8"

    relayhost = cfg.get("relayhost") or os.environ.get("RELAYHOST") or "[smtp.office365.com]:587"

    def _tls_level(v: str, default: str) -> str:
        vv = str(v or "").strip().lower()
        if vv in ("none", "may", "encrypt", "verify", "secure"):
            return vv
        return default

    tls_cfg = cfg.get("tls") or {}
    tls_25 = _tls_level(tls_cfg.get("smtpd_25") or os.environ.get("RELAY_SMTPD_TLS_LEVEL_25"), "may")
    tls_587 = _tls_level(tls_cfg.get("smtpd_587") or os.environ.get("RELAY_SMTPD_TLS_LEVEL_587"), "encrypt")
    tls_out = _tls_level(tls_cfg.get("smtp_out") or os.environ.get("RELAY_SMTP_TLS_SECURITY_LEVEL"), "secure")

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    # Runtime configuration is authoritative after onboarding. Environment
    # values remain a bootstrap fallback for legacy/headless deployments.
    ms365_user = str((cfg or {}).get("ms365_smtp_user") or "").strip() or os.environ.get("MS365_SMTP_USER", "").strip()

    oauth = (cfg or {}).get("oauth") or {}
    tenant_id = str(oauth.get("tenant_id") or os.environ.get("MS365_TENANT_ID") or "").strip()
    client_id = str(oauth.get("client_id") or os.environ.get("MS365_CLIENT_ID") or "").strip()

    import re as _re
    # Entra object IDs use the GUID text shape, but are not guaranteed to
    # carry RFC 4122 version/variant bits.
    guid = _re.compile(r"^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$", _re.I)
    if tenant_id and not guid.fullmatch(tenant_id):
        raise ValueError("tenant_id must be a canonical GUID")
    if client_id and not guid.fullmatch(client_id):
        raise ValueError("client_id must be a canonical GUID")
    if ms365_user and tls_out not in ("verify", "secure") and os.environ.get("ALLOW_INSECURE_OUTBOUND_SMTP", "0") != "1":
        raise ValueError("OAuth relay requires authenticated outbound TLS; set smtp_out=secure or explicitly opt into ALLOW_INSECURE_OUTBOUND_SMTP=1")

    if ms365_user:
        outbound_sasl_block = "\n".join(
            [
                "smtp_sasl_auth_enable = yes",
                "smtp_sasl_password_maps = lmdb:/etc/postfix/sasl_passwd",
                "smtp_sasl_security_options =",
                "smtp_sasl_mechanism_filter = xoauth2",
            ]
        )
    else:
        # Dev/test mode (e.g. MailHog): allow unauthenticated relayhost.
        outbound_sasl_block = "smtp_sasl_auth_enable = no"

    main_cf = MAIN_CF_TEMPLATE.format(
        hostname=_safe_cf_value(hostname),
        domain=_safe_cf_value(domain),
        relayhost=_safe_cf_value(relayhost),
        mynetworks=_safe_cf_value(mynetworks),
        tls_cert=_safe_cf_value(args.tls_cert),
        tls_key=_safe_cf_value(args.tls_key),
        smtp_tls_security_level=_safe_cf_value(tls_out),
        outbound_sasl_block=outbound_sasl_block,
    )
    (outdir / "main.cf").write_text(main_cf, encoding="utf-8")
    (outdir / "master.cf").write_text(MASTER_CF.format(tls_25=tls_25, tls_587=tls_587), encoding="utf-8")

    # Render sasl-xoauth2 config so OAuth settings take effect without container restart.
    # (The sasl-xoauth2 plugin reads this file at runtime.)
    sx_path = os.environ.get("SASL_XOAUTH2_CONFIG", "/etc/sasl-xoauth2.conf")
    try:
        # Validation renders must not mutate the live OAuth plugin config.
        sxp = Path(sx_path) if outdir == Path("/etc/postfix") else outdir / "sasl-xoauth2.conf"
        if tenant_id and client_id:
            cfg_obj = {
                "client_id": client_id,
                "client_secret": "",
                "token_endpoint": f"https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token",
                "log_full_trace_on_failure": os.environ.get("OAUTH_LOG_FULL_TRACE", "no"),
                "log_to_syslog_on_failure": os.environ.get("OAUTH_LOG_TO_SYSLOG", "yes"),
            }
            sxp.write_text(json.dumps(cfg_obj, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        else:
            # Avoid keeping stale config around on fresh installs.
            try:
                sxp.unlink(missing_ok=True)
            except Exception:
                pass
    except Exception:
        # Best-effort only
        pass

    # Outbound xoauth2 token file mapping
    sasl_passwd = outdir / "sasl_passwd"
    if ms365_user:
        # token file path must be a safe filename
        import re as _re
        safe = _re.sub(r"[^A-Za-z0-9_.@+\-]", "_", ms365_user.strip())
        while ".." in safe:
            safe = safe.replace("..", "__")
        safe = safe.strip("._-")[:128]
        token_file = str(Path(args.token_dir) / safe)
        sasl_passwd.write_text(f"{relayhost} {ms365_user}:{token_file}\n", encoding="utf-8")
        os.chmod(sasl_passwd, 0o600)
        postmap(sasl_passwd)

    # Sender login map (envelope sender -> comma-separated sasl logins)
    # LMDB map keys are unique, so users sharing an address must be aggregated.
    allowed_from = cfg.get("allowed_from", {}) or {}
    sender_login_maps = outdir / "sender_login_maps"
    sender_login_maps.write_text(
        render_sender_login_map(allowed_from), encoding="utf-8"
    )
    postmap(sender_login_maps)

    # Sender canonical map: rewrite DSN-ish senders to the MS365 identity.
    # This avoids M365 rejecting MAILER-DAEMON / postmaster envelope senders.
    sender_canonical = outdir / "sender_canonical"
    canon_lines = []
    if ms365_user:
        canon_lines.extend(
            [
                f"MAILER-DAEMON {ms365_user}\n",
                f"postmaster {ms365_user}\n",
                f"MAILER-DAEMON@{domain} {ms365_user}\n",
                f"postmaster@{domain} {ms365_user}\n",
                f"MAILER-DAEMON@{hostname} {ms365_user}\n",
                f"postmaster@{hostname} {ms365_user}\n",
            ]
        )
    sender_canonical.write_text("".join(canon_lines), encoding="utf-8")
    postmap(sender_canonical)


if __name__ == "__main__":
    main()
